### ISSUE TITLE
Anything I try gives "unbound variable" error in console

### ISSUE THREAD

**Issue by Zireael07** [actonDev/s7-playground#1]
I tried both (display "hi there") and (+ 1 2 3)

**Comment by actondev** [comment]
![image](https://user-images.githubusercontent.com/1299928/94051217-8470c380-fdd7-11ea-89d1-ff6732a192f3.png)
It's even working in the hosting of github. Does this work on you? https://actondev.github.io/s7-playground/

**Comment by Zireael07** [comment]
That's weird, now it works too (I first entered the site by clicking the link on the repo main page). Maybe some weird hiccup on my browser's end?

**Comment by actondev** [comment]
Glad it works.
May I ask how you stumbled upon this one? :) I'm asking cause the plan here would to make some interactive (s7) scheme tutorial page. Something like https://doc.rust-lang.org/book/ch03-03-how-functions-work.html for example.

I'm mentioning just in case you'd be interested :)

**Comment by Zireael07** [comment]
I stumbled onto the repo as such on s7 web page https://ccrma.stanford.edu/software/snd/snd/s7.html although the link to the repo is super poorly visible.

An interactive tutorial page for s7 would be awesome <3 <3 <3

**Comment by actondev** [comment]
Huh, hadn't noticed that link was added there! Thanks for pointing that out.

So, the pitch: The idea is to do the website in ClojureScript. Let me know if you'd be interested in collaborating/helping/you name it :)
